# Variável Aleatória Contínua

## Distribuições contínuas

Para entender a diferença entre variável aleatória discreta e a variável aleatória contínua  é necessário definir cada uma delas:

- Variável Aleatório Discreta: assume valores específicos. Exemplo: número de clientes que entram na loja, número de mortes, número de nascimentos, etc.

- Variável Aleatória Contínua: assume qualquer valor no domínio dos número reais. Por isso entre os valores 2 e 3, por exemplo, pode existir infinitos valores para uma variável aleatória contínua. Exemplo: peso, altura, preço de commodities, temperatura, quantidade de chuva em milímetros, etc. 

@Sartoris2013 exemplica as duas situações de variáveis discretas e contínuas usando o exemplo de relógio digital e de relógio analógico considerando somente a hora como valor da variável. No caso do relógio digital a mudança de valor ocorre de forma discreta, diferentemente da situação do relógio analógico que a mudança de horas é de forma gradual.

Para o caso discreto é possível calcular a probabidade para os valores específicos. Por isso 
\[
P(2<x<3) \neq P(2\leq x \leq 3) \neq P(2 < x \leq 3) \neq P(2\leq x < 3)
\]

Já para o caso contínuo não é possível calcular a probabilidade para um valor específico da variável. Inclusive, no limite, a probilidade de um valor específico para uma variável aleatória contínua é igual zero. Portanto,

\[
P(2<x<3) = P(2\leq x \leq 3) = P(2 < x \leq 3) = P(2\leq x < 3)
\]

A situação do exemplo do relógio analógico do @Sartoris2013, como a mudança de hora ocorre de forma gradual e a probabilidade é igual para qualquer valor da hora, trata-se de uma distribuição de probabilidade uniforme contínua. Grafico gerado usando a função `gglot` do pacote  `ggplot2`.

```{r DistribuicaoUniformeContinua, echo=TRUE}
library(ggplot2)

hora <- c(1,2,3,4,5,6,7,8,9,10,11,12)
prob <- c(1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12,1/12)
horaanalogica <- as.data.frame(cbind(hora, prob))
horaanalogica

ggplot(horaanalogica, aes(hora, prob)) +
  geom_line() +
  xlim(0,13) + ylim(0,0.20) +
  scale_x_continuous(breaks = seq(1,12, by = 1))
```


Nesta situação, matematicamamente faz sentido calcular a probabilidade para um intervalo de valores da variável e não para valores específicos com é no caso da variável aleatória discreta. Dessa forma com a função de probabilidade da distribuição, denominada de **função densidade de probabilidade** (f.d.p.), pode-se obter a probabilidade obtendo a área abaixo da curva desta função. Matematicamente, a probabilidade pode ser obtida através da integral definida desta função para o intervalo de valores em questão.

Note que para $f(x)$ ser função densidade de probabilidade, precisa atender as seguintes propriedades definidas pela teoria da probabilidade:

- a soma das probabilidades para todo os valores definidos da variável $x$ dever ser igual a 1.
- a probabilidade obtida através de $f(x)$ não pode ser negativa. 

No exemplo da relógio analógico a probabilidade da hora estar entre 2 e 3 é a área da curva ou reta da distribuição uniforme contínua cujo valor constante da probabilidade é $1/12$. O intervalo entre 2 e 3 proporciona um intervalo equivalente a unidade, uma vez que intervalo pode ser calculado entre a diferença entre o valor final e o valor inicial. Dessa forma:

\[
P(2 < x < 3) = \dfrac{1}{12} \times \left( 3 - 2 \right) = \dfrac{1}{12},
\]
ou seja,
\[
P(2<x<3) = P(2\leq x \leq 3) = P(2 < x \leq 3) = P(2\leq x < 3) = \dfrac{1}{12}
\]

**Exemplo numérico sobre função densidade de probabilidade**

Exemplo 4.1.3 da página 79 do @Sartoris2013. Dada a função densidade de probabilidade da variável aleatória contínua mostrada a seguir 

\[
  f(x) = 
    \begin{cases}
      Ax~~0\leq x \leq 3\\
      0,~~X<0~\text{ou}~x>3\\
    \end{cases}
\]

a) Determine o valor de A.

**Resposta**: Dado que $f(x) = Ax$

\[
  f(3) = 3A
\]
para $x = 3$ e 
\[
  f(0)  = 0
\]
para $x=0$

Graficamente seria um triângulo de de base 3 e altura de 3A. Como a função definida de modo que
\[
  f(x) \geq 0
\]
ou seja resulte valores não-negativos, basta igualar a área a 1, pois a soma das probabilidades para todos os valores definidos para a variável $x$ deve ser igual a 1. Portanto a probabilidade é a área correspondente ao triangulo de base 3 e altura 3A. Ou seja,
\[
  \dfrac{3A \times 3}{2} = 1
\]
e 
por isso
\[
  A = \dfrac{2}{9}
\]
Ou seja, 
\[
  f(x) = 3x
\]

b) Determine a probabilidade de que $x$ esteja entre 2 e 3.

Para $x=2$ se tem
\[
  f(2) = 2\times \dfrac{2}{9} = \dfrac{4}{9}
\]
e para $x=3$
\[
f(3) = 3 \times \dfrac{2}{9} = \dfrac{2}{3}
\]
A área correspondente a probababilidade de $x$ estar entre 2 e 3 pode ser obtida subtraindo a área do triângulo maior que seria com $x$ entre 0 e 3 e o triângulo menor com $x$ entre 2 e 3. Ou seja, a área do triangulo maior é calculado como

\[
  \text{triângulo menor} = 3\times \dfrac{2}{3} \times \dfrac{1}{2} = 1
\]

e a área do triângulo menor é calculado como

\[
  \text{triângulo menor} = 2\times \dfrac{4}{9} \times \dfrac{1}{2} = \dfrac{4}{9}.
\]
Assim a diferença das áreas do triângulo maior e do triângulo menor é igual a $5/9$. Ou seja,

\[
  P(2<x<3) = 1 - \dfrac{4}{9} = \dfrac{5}{9}
\]

**Segundo exemplo númerico sobre função densidade de probabilidade**

Exemplo 4.1.4 da página 80 do @Sartoris2013. Dada da f.d.p. ded uma variável aleatória contínua,

\[
  f(x) = 
    \begin{cases}
      Ax^2~~0\leq x \leq 1\\
      0,~~X<0~\text{ou}~x>1\\
    \end{cases}
  \]

a) Determine o valor da constante A.
Note que a função já não é mais do tipo linear e por isso não é necessário utilizar a integral da função em questão para calcular a probabilidade. Considerando novamente que a soma das probabilidades para todos os valores definidos para a variável $x$ deve ser igual a um, se tem

\[
\int_{-\infty}^{+\infty} f(x)\text{d}x = 1
\]
Para este exemplo, a função $f(x)$ só está definido para os valores entre 0 e 1, sendo que para valores de $x$ menor que 0 e valores de $x$ maior que 1 a função $f(x)$ assume valor igual a zero. Portanto,

\[
\int_{0}^{1} Ax^2\text{d}x = 1
\]
Como A é constante, pode-se colocar para fora da integral

\[
  A\int_{0}^{1} x^2\text{d}x = 1
\]
Calculando a integral definida
\[
  A\left[ \dfrac{x^3}{3} \right]_{0}^{1} = 1
\]
Avaliando para os valores 1 e 0 e depois realizando a diferença
\[
  A\left[ \dfrac{1}{3} - \dfrac{0}{3} \right]_{0}^{1} = 1
\]
Ou seja,
\[
  A = 3.
\]
Ou seja a função é

\[
  f(x) = 3x^2.
\]

b) Dtermine a probabilidade de que $x$ esteja entre 0,5 e 1. 

Primeiramente verifica-se que tanto 0,5 como 1 são valores que estão dentro do intervalo de $x$ definido para a função em questão. Por exemplo, se um dos limites fosse igual a 2, consideraria $x=1$ pois $f(x)=0$ para $x>1$. Por isso basta calcular a integral da função para os valores de $x$ entre 0,5 e 1. Ou seja,

\[
  P(0,5\leq x \leq 1) = \int_{0,5}^{1} 3x^3\text{d}x 
\]
\[
  P(0,5\leq x \leq 1) = \left[ \frac{3x^3}{3}  \right]_{0,5}^{1}
\]
\[
  P(0,5\leq x \leq 1) = 1^3 - 0,5^3 = 1 - 0,125 = 0,875.
\]
Resumindo, para que uma função qualquer seja uma função densidade de probabilidade precisa atender duas condições:

\[
  \int_{-\infty}^{+\infty} f(x) \text{d}x = 1
\]
e 
\[
  f(x) \geq 0~~\text{para todos os valores de}~x
\]

**Exemplo numérico sobre a distribuição exponencial**

O exemplo 4.1.5 da página 82 de @Sartoris2013 é uma simples aplicação para a distribuição exponencial. Dada a f.d.p. da varíável aleatória contínua $x$
\[
  f(x) =
    \begin{cases}
      Ae^{-\alpha x},~~\text{para }~x\geq 0 \\
      0,~~\text{para }~~x<0
    \end{cases}
\]
a) Determine o valor de A.
Então como foi informado no anunciado do exemplo numérico, essa distribuição especial é conhecida com distribuição exponencial. Como

\[
  \int_{-\infty}^{+\infty} f(x) \text{d}x = 1
\]

e a função assume valores iguais a zero para valores negativos de $x$, se tem

\[
  \int_ {0}^{+\infty} A e^{-\alpha x} = 1.
\]
Como A é constante, pode-se colocar par fora da integral
\[
  A\int_{0}^{+\infty} e^{-\alpha x}\text{d}x = 1
\]
e sabendo que a integral da função é um pouco diferente, considerando que há um $\alpha$ multiplicando $x$, temos

\[
  A\left[ \dfrac{e^{-\alpha x}}{-\alpha} \right]_{0}^{+\infty} = 1
\]

\[
  A\left[0  - \left(-\dfrac{1}{\alpha}\right)\right] = 1
\]
Portanto,

\[
A = \alpha
\]

### Função de distribuição de variáveis contínuas

A semelhança do caso das variáveis discretas, a **função de distribuição acumulada ** ou **função de distribuição** $F(x)$ é a soma da probabilidades de todos os valores possíveis que a variável $x$ pode assumir até o valor de $x$ propriamente dito. Isso é feito através da integral da seguinte forma

\[
  F(x) = \int_{-\infty}^{x} f(t) \text{d}t.
\]

Portanto, matematicamente,$f(x)$ é a derivda da função $F(x)$
\[
  f(x) = \dfrac{\text{d}F(x)}{\text{d}x}.
\]

**Exemplo numérico da função de distribuição**

O exemplo 4.2.1 da página 83 do @Sartoris2013, trata-se da obtenção da função distribuição exponencial através da sua respectiva função densidade de probabilidade. Dada a função f.d.p.da dsitribuição exponencial, determine a função de distribuição correspondente.

\[
  f(x) = 
  \begin{cases}
    e^{-x},~~\text{para }~ x \geq 0\\
    0,~~\text{para } x< 0
  \end{cases}
\]
Dado que a função só é definido para $x\geq 0$, o limite de integração inferior é zero.

\[
  F(x) = \int_{0}^{+\infty} f(t)\text{d}t
\]
substituindo a f.d.p.
\[
  F(x) = \int_{0}^{+\infty} e^{-t}\text{d}t
\]
lembrando a integral de $e^{-x}$ e que todo número elevado a zero é igual a um
\[
F(x) = \left[ -e^{-t}  \right]_{0}^{x}.
\]
Assim,
\[
F(x) = -e^{-x} + e^{0}
\]
e
\[
F(x) = 1 - e^{-x}
\]
Portanto a função distribuição é dada por

\[
  F(x) =
  \begin{cases}
    1 - e^{-x},~~\text{para } x\geq 0 \\
    0,~~\text{para } x\leq 0
  \end{cases}
\]

**Segundo Exemplo numérico sobre função de distrubuição**

Exemplo 4.2.2 da página 84 de @Sartoris2013. 

## Distribuição Normal

## Teorema de Tchebichev

