--- 
title: "Notas de aulas de Estatística Econômica"
author: "Marcos Minoru Hasegawa"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: abntex2
link-citations: yes
description: "Trata-se do material usado nas aulas de Estatística Econômica e Introdução à Econometria SE305 do curso de Economia da Universidade Federal do Paranà."
---

```{r setup, include=FALSE}
library(formatR)
library(knitr)
library(ggplot2)
knitr::opts_chunk$set(
	echo = TRUE,
	error = FALSE,
	fig.height = 4,
	fig.width = 4,
	message = FALSE,
	warning = FALSE,
	cache = FALSE,
	tidy = TRUE,
	tidy.opts = list(width.cutoff = 50)
)
options(OutDec = ",")
```

# Licença {-}

Como está descrito no repositório, os poucos códigos originais desenvolvidos ao longo do texto estão sob a licença **GNU GPLv3** .

O texto e as artes gráficas elaboradas de forma original estão sob licença **Creative Commons BY-NC-SA 4.0**.

# Pré-requisitos

## LaTeX e R

- LaTeX
  - Windows: ProTEXt (MikTEX) -- Editor TEXStudio
  - XOS/Mac: MacTEX -- Editor TEX Shop
  - Linux: TEX live -- Editor TEX Works

- R
  - Windows/XOS/Linux: R -- Editor RStudio

- R Markdown (disponível no RStudio)
  - HTML
  - PDF
  - LaTeX~ e Beamer
  - MS-Word

## Intalando R, RStudio, MikTEX e TEXstudio


1) Baixar as instalação compatível com o seu sistema operacional em: \href{http:www.r-project.org}{http:www.r-project.org} e instalar primeiro.
2) Baixar o ProTEXt para Windows, MacTEX para xOS e TEX Live para Linux em \href{http:www.tug.org}{http:www.tug.org} instalar depois do R. Instalar a versão completa. Esta instalação deveria ser realizada com tempo por ser demorada.
3) Baixar o RStudio Desktop compatível com o seu sistema operacional em: \href{http:www.rstudio.com}{http:www.rstudio.com} e instalar depois do ProTEXt ou MacTEX ou TEX Live.
4) Baixar o TEXstudio em \href{http:www.texstudio.org}{http:www.texstudio.org} e instalar por último.

## UTF-8 e acentuação direta no teclado

- Usar o código de fonte UTF-8 que no RStudio pode ser feito e Global
Options/Code/Saving/DefaultTextEncoding
- no cabeçalho dos arquivos LaTeX ou no arquivo "in header.txt"~ inclua os seguintes pacotes:
  - usepackage[brazil]{babel}
  - usepackage[utf8]{inputenc}
  - usepackage[T1]{fontenc}

## Como aprender o LaTeX 

- aula expressa no laboratório previsto na disciplina SE305. Só o básico. O slide tem muita informação para consulta.

- material na internet **GRÁTIS**, inclusive livros em pdf 

- tutoriais e vídeo aulas **GRÁTIS** no YouTube

- a ajuda e exemplos do Overleaf que é apresentado no próximo slide.

- geralmente disponibilizo os códigos dos arquivos \LaTeX\, Sweave e R Markdown do material das minhas aulas. 
  - Note que no R Markdown tem uma mistura de \LaTeX\ e R Markdown.
  - Procure pelas extensões: \*.tex, \*.Rwd e \*.Rmd.
